### ISSUE TITLE
converter.axisX.min and converter.axisY.min is undefined

### ISSUE THREAD

**Issue by Kieftenbelt** [amichair/chartist-plugin-drag#2]
First of all, really awesome that you took time in building this, much appreciate.

As a simple try-out;
```
new Chartist.Line('.ct-chart', {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  series: [
    [5, 2, 4, 2, 0]
  ]
}, {
      plugins: [
        Chartist.plugins.drag({
           // settings here
        })
      ]
    }); 
```

Gives me the return of 

> undefined is not an object (evaluating 'data.axisX.range')

I've tried older versions of Chartist as well, but gave me the same issue unfortunately. 
The issue should start from initialising the data when points are first drawn, so the data from Chartist itself doesn't have the vars she needs.

Hope you can help me out, many thanks!

EDIT: 
So far I can see, in object data.axisX there is no range, but in axisY there is?

**Comment by amichair** [comment]
Indeed, the original implementation was intended for use with line graphs with x,y numeric values only.

I now updated it to also support simple label+value graphs such as the example you provided (thanks for that!). I hope it works in your real use case...

**Comment by Kieftenbelt** [comment]
Many thanks for the update, works like it should!
